### ISSUE TITLE
Issues with responsiveness

### ISSUE THREAD

**Issue by pmochine** [lucaspulliese/vue-cool-lightbox#29]
So I love this package so much! You deserve much more love.

But I have an issue with my responsiveness, even though your demo examples are working! Super weird.

Here have a look:

![Ohne-Titel (1)](https://user-images.githubusercontent.com/25006691/80027114-86122480-84e3-11ea-88a2-c063e63df67b.gif)

Not sure why it is like that. Maybe because `<CoolLightBox` is quite nested. Or maybe because I'm using gridsome?

Another think I notice that when the resize event is fired, the style is not updated:

<img width="482" alt="Bildschirmfoto 2020-04-22 um 21 54 10" src="https://user-images.githubusercontent.com/25006691/80027330-e0ab8080-84e3-11ea-9133-d6db972cf29d.png">

Sorry that I'm not uploading a demo with the problem. I'm just too lazy and I hope you might know whats up.

Cheers from Berlin

**Comment by lucaspulliese** [comment]
Hi @pmochine! 

First of all, thank you for your words, I really appreciate it!

Both problems are because that translate3d is calculated based on windows width, that's only fired when the lightbox is open and when the lightbox changes the current slide. So I have to fire that "calculation" when the user is resizing the website.

I will be working on it in the new release. 

Cheers!

**Comment by pmochine** [comment]
@lucaspulliese Thank you for your response :) Btw I just wanted to add, that this bug is not existing for the first item. Only starting from the second. So you also see the bug on your examples.

Thanks, can't wait for the new release.

**Comment by lucaspulliese** [comment]
Hi @pmochine! 

This issue is fixed in version 2.2.0, If you see that everything works fine please close the issue 😃
